name: Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  avoid_redundancy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
  lint:
    needs: [avoid_redundancy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '16'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn eslint

  test:
    needs: [avoid_redundancy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '16'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test
        run: yarn test:unit
